#+TITLE: NixOS install using official ISO image
#+AUTHOR: Krizdano
#+DESCRIPTION: instructions to install Nixos with my personal configuration using the official NixOS ISO image
#+STARTUP: overview

This file contains instructions to install Nixos with my personal configuration using the official NixOS ISO image.

* Table of Contents :toc:
- [[#download-the-iso][Download the ISO]]
- [[#boot-from-the-usb-drive][Boot from the USB Drive]]
- [[#connect-to-internet][Connect to Internet]]
- [[#manual-partitioning-and-mounting][Manual Partitioning and Mounting]]
- [[#automated-partitioning-and-mounting-with-disko][Automated Partitioning and Mounting with Disko]]
  - [[#clone-this-repo][Clone this Repo]]
  - [[#run-disko][Run Disko]]
  - [[#generate-hardware-configuration][Generate Hardware Configuration]]
  - [[#edit-hardware-configurationnix][Edit hardware-configuration.nix]]
  - [[#install-nixos][Install NixOS]]
  - [[#reboot][Reboot]]

* Download the ISO
Download the latest NixOS ISO image from the [[https://nixos.org/download/][NixOS download page]] and create a bootable USB drive using tools like ~dd~, [[https://rufus.ie/][Rufus]], or [[https://www.balena.io/etcher][Etcher]].

I am using ~dd~.

#+begin_src bash
  sudo dd if=/path/to/official-nixos.iso of=/dev/diskname bs=1M
#+end_src

* Boot from the USB Drive
Insert the bootable USB drive into your machine and boot from it.

You are logged-in automatically as nixos. The nixos user account has an empty password so you can use sudo without a password

#+begin_src bash
  sudo -i
#+end_src

* Connect to Internet
According to the [[https://nixos.org/manual/nixos/stable/#sec-installation-manual-networking][NixOS Manual]], If you are using the graphical installer, you can configure the network, wifi included,
through [[https://networkmanager.dev/][NetworkManager]].

I use [[https://networkmanager.dev/docs/api/latest/nmcli.html][nmcli]].

#+begin_src bash
  nmcli device wifi connect SSID
#+end_src

On the minimal installer, [[https://networkmanager.dev/][NetworkManager]] is not available, so configuration must be performed using ~wpa_cli~.
To configure the wifi, first start ~wpa_supplicant~ with =systemctl start wpa_supplicant=, then run =wpa_cli=.
For most home networks, you need to type in the following commands.

#+begin_example
> add_network
0
> set_network 0 ssid "myhomenetwork"
OK
> set_network 0 psk "mypassword"
OK
> set_network 0 key_mgmt WPA-PSK
OK
> enable_network 0
OK
#+end_example

When successfully connected, you should see a line such as this one.

#+begin_example
<3>CTRL-EVENT-CONNECTED - Connection to 32:85:ab:ef:24:5c completed [id=0 id_str=]
#+end_example

You can now leave ~wpa_cli~ by typing ~quit~.

For more detailed instructions, see the [[https://nixos.org/manual/nixos/stable/#sec-installation-manual-networking][Manual]].

* Manual Partitioning and Mounting
If you prefer to Manually partition your disks and mount your partitions, [[file:nixos-manual-partitioning-and-mounting.org][follow these instructions]].
This can be used in case [[https://github.com/nix-community/disko][disko]] fails.

* Automated Partitioning and Mounting with [[https://github.com/nix-community/disko][Disko]]
** Clone this Repo
:PROPERTIES:
:CUSTOM_ID: Clone-this-repository
:END:

#+begin_src bash
  nix-shell -p git
  git clone https://github.com/Krizdano/nixos-config.git nixconfig
#+end_src

** Run Disko
- disko-install: TODO

#+begin_src bash
  cd nixconfig
  nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode disko ./disko.nix --arg device '"/dev/diskname"'
#+end_src

If you don't want to generate a new ~hardware-configuration.nix~, you can just run

#+begin_src bash
  nixos-install --flake .#Felix
#+end_src

and ~reboot~ your system to finish the installation.
If you do want to generate a new ~hardware-configuration.nix~, follow these steps.


** Generate Hardware Configuration

#+begin_src bash
  nixos-generate-config --show-hardware-config --no-filesystems --root /mnt > hosts/felix/hardware-configuration.nix
#+end_src

This command creates ~hardware-configuration.nix~ file that omits everything concerning ~file systems~ and ~swap devices~ from the =hardware configuration=.

** Edit hardware-configuration.nix

Remove some options that are automatically generated by ~nixos-generate-config~ inside ~hardware-configuration.nix~.

- ~networking.useDHCP~
  - It is already defined in [[file:../hosts/felix/default.nix][hosts/felix/default.nix]]
  - Remove it from newly generated [[file:../hosts/felix/hardware-configuration.nix][hardware-configuration.nix]]
- ~nixpkgs.hostPlatform~
  - It is already defined in [[file:../flake.nix][flake.nix]]
  - Remove it from new generated [[file:../hosts/felix/hardware-configuration.nix][hardware-configuration.nix]]

#+begin_quote
Removing these options are not necessary. It is done to avoid duplication.
#+end_quote

#+begin_src bash
  nano hosts/felix/hardware-configuration.nix
#+end_src

If you want vim
#+begin_src bash
  nix-shell -p vim # or neovim
  vim hosts/felix/hardware-configuration.nix
#+end_src

** Install NixOS
#+begin_src bash
  nixos-install --flake .#Felix
#+end_src

Follow the prompts to set the *root* password and complete the installation.

#+begin_quote
NOTE: The *root* password and *user* password will be reset to ~test~ after reboot.
You can change it by editing [[file:../templates/secrets.nix][templates/secrets.nix]]. see section [[file:../README.org::#changing-the-username-and-password][changing username and password]] for more info.
#+end_quote

After you install ~NixOS~ with this config, any changes you made to the config won’t be saved
after a reboot unless you save them somewhere persistent. Make sure to save them somewhere inside the ~/mnt~ directory.
for example

#+begin_src bash
  cd ../
  cp -r nixconfig /mnt/persist/
#+end_src


The default place where ~NixOS~ looks for configurations are inside ~/etc/nixos~ (~/mnt/etc/nixos~ in this case). I currently keep
the configuration files inside (~/mnt~) ~/persist/home/.config/nixconfig~ which links to ~/home/user/.config/nixconfig~. If you plan to change
the configuration location make sure to update ~$NIXOS_CONFIG~ variable inside [[file:../modules/home/default.nix::NIXOS_CONFIG][modules/home/default.nix]]

** Reboot
Your installation is complete. Now go ahead and reboot your system.

#+begin_src bash
  reboot
#+end_src

Remove the USB drive and boot into your newly installed NixOS system.
